TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += PearlPC.proto

DB += devPearl.db
DB += test_pvs.db

#=======================================
include $(TOP)/configure/RULES
